### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by draffensperger** [samvel1024/kbct#33]
For use of software in a work context, it's nice to have a license and I've noticed that `kbct` doesn't have one. Would you be willing to add one?

**Comment by geekley** [comment]
Having a license is essential. Otherwise there's no way to know what can be done with both code AND program. Not to mention it's difficult to trust code with no license at all (and this requires sudo!).
If it's open-sourced, others are allowed to fork, distribute, and might eventually include it in repos for e.g. `apt`.
Or, if it's proprietary, you should say so, or people will make incorrect assumptions (e.g. when contributing).
Open source license suggestions:
- MIT: if you require nothing except attribution
- Unlicense: to put it in public domain, no requirements
- GPL: to forbid inclusion in closed-source software + lots of other rules

**Comment by LifeCANvs** [comment]
@samvel1024 Is this project still maintained? Would you mind adding the license which applies to the code in this project so people can know whether we are allowed the even use your awesome tool at all... and to what extend your code may or may not be used to build on and perhaps create even more useful tools from it. Without a license, I believe that it is illegal to use your creation at all - such a pity for it to go to waste :(

**Comment by samvel1024** [comment]
Added, thanks

**Comment by LifeCANvs** [comment]
> Added, thanks

Thank you so much!
